[workspace]
members = [
    "candle-core",
    "candle-examples",
    "candle-kernels",
    "candle-hub",
    "candle-nn",
    "candle-pyo3",
]

[profile.release-with-debug]
inherits = "release"
debug = true
