[package]
name = "candle-transformers"
version = "0.1.0"
edition = "2021"

description = "Pretrained models and inference API for the candle ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
candle = { path = "../candle-core" }
candle-hub = { path = "../candle-hub" }
candle-nn = { path = "../candle-nn" }
intel-mkl-src = { workspace = true, optional = true, features = ["mkl-dynamic-lp64-iomp"]}
tokenizers = { workspace = true, features = ["onig"] }
rand = { workspace = true }
wav = { workspace = true }

[features]
default = []
cuda = ["candle/cuda", "candle-nn/cuda"]
mkl = ["dep:intel-mkl-src", "candle/mkl", "candle-nn/mkl"]
