[package]
name = "candle-wasm"
version = "0.1.0"
edition = "2021"

description = "Wasm example for the candle ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle = { path = "../candle-core", default-features=false }
candle-nn = { path = "../candle-nn", default-features=false }
wasm-bindgen = "0.2.87"
getrandom = { version = "0.2", features = ["js"] }

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]
