[package]
name = "candle-nn"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
candle = { path = "../candle-core", version = "0.1.0", package = "candle-core" }
thiserror = { workspace = true }
intel-mkl-src = { workspace = true, optional = true }
safetensors = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[features]
default = []
cuda = ["candle/cuda"]
mkl = ["dep:intel-mkl-src", "candle/mkl"]
