[package]
name = "candle-nn"
version = "0.1.0"
edition = "2021"

description = "Minimalist ML framework."
repository = "https://github.com/LaurentMazare/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT/Apache-2.0"
readme = "README.md"

[dependencies]
candle = { path = "../candle-core", version = "0.1.0", package = "candle-core" }
thiserror = { workspace = true }
intel-mkl-src = { workspace = true, optional = true }
safetensors = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }

[features]
default = []
cuda = ["candle/cuda"]
mkl = ["dep:intel-mkl-src", "candle/mkl"]
