[package]
name = "candle-metal-kernels"
version = "0.3.0"
edition = "2021"

description = "CUDA kernels for Candle"
repository = "https://github.com/huggingface/candle"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]
metal = { workspace = true }
once_cell = "1.18.0"
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
half = { workspace = true }
